# Nom pour le workflow
name: Premier workflow

on: 
    push:
        branches:
            - main
            
    workflow_dispatch:
jobs:
    first-save:
        runs-on: ubuntu-20.04

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        - run: mvn install dependency
    second-job:
        runs-on: ubuntu-20.04        
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
            cache-dependency-path: 'exercice1/src/main/ressource/pom.xml' 
        - run: mvn -B package --file pom.xml

